import LayoutContext from "context/layoutContext/layout-context";
import Head from "next/head";
import { useContext } from "react";
import styles from "styles/pageStyles/product.styles.module.scss";

export default function Home() {
  const { homePageConfig } = useContext(LayoutContext);
  return (
    <div className={styles.productPageContainer}>
      <Head>
        <title>Valeenchy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.productPageSectionContainer}></section>
    </div>
  );
}
