import { ThemeProvider } from "@emotion/react";
import Layout from "components/Layout";
import Head from "next/head";
import { defaultTheme } from "styles/theme";

export default function Home() {
  return (
    <>
      <Head>
        <title>Valeenchy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={defaultTheme}>
        <Layout>
          <h1>Hello World!</h1>
        </Layout>
      </ThemeProvider>
    </>
  );
}
