import CardSlider from "components/CardSlider";
import { CARD_SLIDER_TYPES } from "components/CardSlider/types";
import CollapsibleComponent from "components/CollapsibleComponent";
import ConfigurablePhotoCollage from "components/ConfigurablePhotoCollage";
import { CONFIGURABLE_IMAGE_TYPE } from "components/ConfigurablePhotoCollage/types";
import SingleMediaRendered from "components/SingleMediaRenderer";
import { SingleMediaOptions } from "components/SingleMediaRenderer/types";
import LayoutContext from "context/layoutContext/layout-context";
import Head from "next/head";
import { useContext } from "react";
import styles from "styles/pageStyles/index.styles.module.scss";
import { homePageCenterOverlayTextContainerStyles } from "../styles/pageStyles/index.styles";

export default function Home() {
  const { homePageConfig } = useContext(LayoutContext);
  return (
    <div className={styles.homePageContainer}>
      <Head>
        <title>Valeenchy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.homePageSectionContainer}>
        <SingleMediaRendered
          url={homePageConfig?.centerImageObject?.url}
          mediaStyles={styles.homePageCenterImageMediaStyles}
          containerStyles={styles.homePageCenterImageContainerStyles}
          alt={homePageConfig?.centerImageObject?.alt}
          type={SingleMediaOptions.IMAGE}
          shouldShowOverlay={true}
          overlayTextConfig={{
            extraContainerStyles: (theme: any) =>
              homePageCenterOverlayTextContainerStyles(theme),
            ...homePageConfig?.centerImageObject?.overlayTextConfig,
          }}
        />
      </section>
      <section className={styles.homePageSectionContainer}>
        <div className={styles.homePageCircleProductSliderContainer}>
          <CardSlider
            slides={homePageConfig.circleCardSlider.items}
            type={CARD_SLIDER_TYPES.IMAGE}
            heading={homePageConfig.circleCardSlider.heading}
            containerStyles={styles.circleImage}
            elementStyles={styles.image}
          />
        </div>
        <div className={styles.homePageSquareProductSliderContainer}>
          <CardSlider
            slides={homePageConfig.squareCardSlider.items}
            type={CARD_SLIDER_TYPES.IMAGE}
            heading={homePageConfig.squareCardSlider.heading}
            containerStyles={styles.squareImage}
            elementStyles={styles.image}
          />
        </div>
      </section>
      <section className={styles.homePageSectionContainer}>
        <div className={styles.homePageCollageContainer}>
          <ConfigurablePhotoCollage
            items={homePageConfig.fiveImageCollage.items}
            type={CONFIGURABLE_IMAGE_TYPE.FIVE_IMAGE_COLLAGE}
          />
        </div>
        <div className={styles.homePageReverseCollageContainer}>
          <ConfigurablePhotoCollage
            items={homePageConfig.fiveImageReverseCollage.items}
            type={CONFIGURABLE_IMAGE_TYPE.FIVE_IMAGE_COLLAGE}
            isFiveCollageReversed
          />
        </div>
      </section>
      <section className={styles.homePageSectionContainer}>
        <div className={styles.homePageReverseCollageContainer}>
          <CollapsibleComponent
            heading={homePageConfig.collapsibleComponent.heading}
            items={homePageConfig.collapsibleComponent.items}
          />
        </div>
      </section>
    </div>
  );
}
